# This file was generated by GoReleaser. DO NOT EDIT.
class UpdateDockerTags < Formula
  desc "CLI to update Docker tag image versions"
  homepage "https://github.com/slimsag/update-docker-tags"
  version "0.5.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/slimsag/update-docker-tags/releases/download/v0.5.0/update-docker-tags_0.5.0_Darwin_x86_64.tar.gz"
    sha256 "1fed3840bce1f0b3b299e96b5b80407db0e39b6019d818413f23c7da3582afd1"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/slimsag/update-docker-tags/releases/download/v0.5.0/update-docker-tags_0.5.0_Linux_x86_64.tar.gz"
      sha256 "32ab4c553058354c85303c9917045a701036b59ba11ee306cfdb1f1151d42d47"
    end
  end
  
  depends_on "go"

  def install
    bin.install "update-docker-tags"
  end

  test do
    system "#{bin}/update-docker-tags --help"
  end
end
